language: node_js
os:
  - osx
osx_image: xcode14.2
node_js:
  - 18.18.0
addons:
  chrome: stable
cache:
  directories:
    - node_modules
    - /Users/travis/Library/Caches/Cypress
install:
  - npm install --legacy-peer-deps
before_script:
  - npm install cypress --force
script:
  - echo "Running tests..."
  - npm run test
  - echo "Running Cypress..."
  - npm run cypress:run
  - echo "Building..."
  - npm run build
  - echo "Deploying..."
  - firebase use --add promotion-project-e8793
  - firebase deploy --token "$FIREBASE_TOKEN"
