language: node_js
os:
  - windows
node_js:
  - 18.18.0
cache:
  directories:
    - node_modules
install:
  - npm install --legacy-peer-deps
script:
  - npm run test
  - npm run cypress:run
  - npm run build
  - firebase deploy --token "1//03ugbGBuzaP3lCgYIARAAGAMSNwF-L9Ir6zW1eWSLUUI1paJ2GiYO5WbJUyzXazaVdVVu4Kk--28DVTlZI5jTI_8fwfM66dZLX1M"
