language: node_js
os:
  - windows
node_js:
  - 18.18.0
addons:
  chrome: stable
install:
  - npm install
before_script:
  - cypress cache clear
  - npm install cypress
script:
  - npm run build
  - npm run test
  - npm run cypress:run

  - firebase use --add promotion-project-e8793
  - firebase deploy --token "$FIREBASE_TOKEN"
